import { useState, useRef, useEffect } from "react";
import { Shield, Search, ShieldAlert, ShieldCheck, Activity, Copy, Download, Info, Loader2, Users, FileText, CheckCircle2 } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { AnalysisResult, HistoryItem } from "./types";
import { ScoreCard } from "./components/ScoreCard";
import { Gauge } from "./components/Gauge";
import { AnalysisHistory } from "./components/AnalysisHistory";
import { cn } from "./lib/utils";

export default function App() {
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const reportRef = useRef<HTMLDivElement>(null);

  // Load history from local storage on mount
  useEffect(() => {
    const saved = localStorage.getItem("social_sec_history");
    if (saved) {
      try {
        setHistory(JSON.parse(saved));
      } catch (e) {
        console.error("Failed to parse history");
      }
    }
  }, []);

  const saveToHistory = (inputStr: string, res: AnalysisResult) => {
    const newItem: HistoryItem = {
      id: Math.random().toString(36).substring(7),
      input: inputStr,
      date: new Date().toISOString(),
      result: res,
    };
    const newHistory = [newItem, ...history].slice(0, 10);
    setHistory(newHistory);
    localStorage.setItem("social_sec_history", JSON.stringify(newHistory));
  };

  const handleAnalyze = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!input.trim()) return;

    setIsLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ input: input.trim() }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to analyze");
      }

      const data: AnalysisResult = await res.json();
      setResult(data);
      saveToHistory(input.trim(), data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  const downloadPDF = async () => {
    if (!reportRef.current || !result) return;
    const canvas = await html2canvas(reportRef.current, { backgroundColor: "#0f172a" });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
    pdf.save(`security_report_${input.replace(/[^a-z0-9]/gi, "_")}.pdf`);
  };

  const copyReport = () => {
    if (!result) return;
    const text = `
Social Media Security AI Analysis
Input: ${input}
Classification: ${result.classification}
Impersonation Risk: ${result.impersonationRisk}
Risk Score: ${result.riskScore}/100
Confidence: ${result.confidenceScore}%

Technical Explanation:
${result.technicalExplanation}

Report generated by Social Media Security AI System.
    `.trim();
    navigator.clipboard.writeText(text);
    alert("Report copied to clipboard.");
  };

  const isHighRisk = result && (result.classification === "FAKE" || result.classification === "BOT-LIKE");

  return (
    <div className="min-h-screen bg-[#0A0B0E] text-slate-200 font-sans selection:bg-blue-500/30">
      <div className="max-w-6xl mx-auto px-4 py-8 sm:py-12">
        {/* Header */}
        <header className="flex flex-col md:flex-row md:items-center justify-between mb-8 pb-6 border-b border-white/5 space-y-4 md:space-y-0">
          <div className="flex items-center space-x-3">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center text-white">
              <Shield className="w-5 h-5" />
            </div>
            <div>
              <span className="text-xl font-bold tracking-tight text-white">SENTINEL<span className="font-light text-blue-500">AI</span></span>
            </div>
          </div>
          <div className="flex items-center gap-6">
            <div className="flex items-center gap-2 px-3 py-1 bg-green-500/10 border border-green-500/20 rounded-full">
              <div className="w-1.5 h-1.5 rounded-full bg-green-500"></div>
              <span className="text-[10px] uppercase tracking-widest text-green-500 font-semibold">System Active</span>
            </div>
          </div>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* Left Column: Input and History */}
          <div className="lg:col-span-4 flex flex-col gap-8">
            <div className="bg-[#0F1117]/50 border border-white/5 rounded-2xl p-6">
              <h3 className="text-[10px] uppercase tracking-widest text-slate-500 font-bold mb-4">Analyze Profile</h3>
              <form onSubmit={handleAnalyze} className="space-y-4">
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-500">
                    <Search className="w-5 h-5" />
                  </div>
                  <input
                    type="text"
                    disabled={isLoading}
                    placeholder="Enter username or profile URL..."
                    className="w-full bg-[#161922] border border-white/10 rounded-2xl py-4 flex-1 px-6 pl-12 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all text-white shadow-2xl placeholder-slate-500"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                  />
                </div>
                <button
                  type="submit"
                  disabled={isLoading || !input.trim()}
                  className="w-full flex justify-center items-center bg-blue-600 hover:bg-blue-500 text-white px-6 py-3 rounded-xl font-semibold shadow-lg shadow-blue-600/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed text-sm"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Analyzing...
                    </>
                  ) : (
                    "Analyze Profile"
                  )}
                </button>
              </form>

              {error && (
                <div className="mt-4 bg-red-500/10 border border-red-500/20 text-red-400 p-3 rounded-lg text-sm flex items-start">
                  <ShieldAlert className="w-4 h-4 mr-2 mt-0.5 shrink-0" />
                  {error}
                </div>
              )}
            </div>

            <div className="bg-[#0F1117]/50 border border-white/5 rounded-2xl p-6 flex flex-col flex-1">
              <h3 className="text-[10px] uppercase tracking-widest text-slate-500 font-bold mb-4">
                Analysis History
              </h3>
              <AnalysisHistory
                history={history}
                onSelect={(item) => {
                  setInput(item.input);
                  setResult(item.result);
                }}
              />
              
              <div className="mt-8 p-4 bg-gradient-to-br from-slate-800 to-slate-900 rounded-xl border border-white/10 flex items-start space-x-3">
                <Info className="w-3.5 h-3.5 text-slate-400 shrink-0 mt-0.5" />
                <p className="text-[11px] text-slate-400 leading-relaxed">Results are estimations based on behavioral patterns and public signals.</p>
              </div>
            </div>
          </div>

          {/* Right Column: Dashboard */}
          <div className="lg:col-span-8">
            <AnimatePresence mode="wait">
              {!result && !isLoading && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="h-[500px] flex flex-col items-center justify-center text-slate-500 border border-white/5 border-dashed rounded-2xl p-12 bg-[#0F1117]/20"
                >
                  <Shield className="w-16 h-16 text-slate-800 mb-4" />
                  <p className="text-lg">System awaiting target identifier.</p>
                  <p className="text-sm mt-2">Enter a username or URL to begin scan.</p>
                </motion.div>
              )}

              {isLoading && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="h-[500px] flex flex-col items-center justify-center rounded-2xl p-12 bg-[#0F1117]/20 border border-white/5"
                >
                  <div className="relative">
                    <div className="w-20 h-20 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
                    <div className="absolute inset-0 flex items-center justify-center">
                      <Shield className="w-6 h-6 text-blue-500 animate-pulse" />
                    </div>
                  </div>
                  <p className="text-blue-400 font-mono mt-6 animate-pulse tracking-widest text-sm uppercase">
                    Analyzing target profile...
                  </p>
                </motion.div>
              )}

              {result && !isLoading && (
                <motion.div
                  key="result"
                  initial={{ opacity: 0, scale: 0.98 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="space-y-6"
                >
                  {/* Action Bar */}
                  <div className="flex justify-end space-x-3">
                    <button onClick={copyReport} className="flex items-center px-3 py-1.5 bg-slate-800 hover:bg-slate-700 border border-white/10 text-white rounded-lg text-xs transition-colors">
                      <Copy className="w-3 h-3 mr-1.5" />
                      Copy
                    </button>
                    <button onClick={downloadPDF} className="flex items-center px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-600/20 rounded-lg text-xs transition-colors">
                      <Download className="w-3 h-3 mr-1.5" />
                      Export PDF
                    </button>
                  </div>

                  <div ref={reportRef} className="space-y-6 pt-1 bg-[#0A0B0E]">
                    {/* Primary Status Card */}
                    <div className={cn(
                      "rounded-2xl p-6 md:p-8 flex flex-col md:flex-row justify-between items-center md:items-start gap-6 border bg-[#161922] overflow-hidden relative",
                      isHighRisk 
                        ? "border-red-500/30" 
                        : "border-emerald-500/30"
                    )}>
                      {/* Background decorative elements */}
                      <div className={cn(
                        "absolute -right-20 -top-20 w-64 h-64 rounded-full blur-3xl opacity-10 pointer-events-none",
                        isHighRisk ? "bg-red-500" : "bg-emerald-500"
                      )}></div>

                      <div className="relative z-10 text-center md:text-left flex-1">
                        <span className={cn(
                           "text-[10px] uppercase tracking-widest font-bold",
                           isHighRisk ? "text-red-500" : "text-emerald-500"
                        )}>Classification</span>
                        <div className="mt-2">
                           <span className="text-3xl lg:text-4xl font-black text-white">{result.classification}</span>
                        </div>
                        <div className="mt-4 flex flex-wrap items-center justify-center md:justify-start gap-2">
                          {isHighRisk ? (
                             <span className="px-2 py-0.5 bg-red-500/20 text-red-400 text-[10px] rounded uppercase font-bold">High Risk</span>
                          ) : (
                             <span className="px-2 py-0.5 bg-emerald-500/20 text-emerald-400 text-[10px] rounded uppercase font-bold">Safe Protocol</span>
                          )}
                          <span className="px-2 py-0.5 bg-slate-800 text-slate-300 border border-white/5 text-[10px] rounded uppercase font-bold">
                            {result.impersonationRisk} Impersonation
                          </span>
                        </div>
                      </div>

                      <div className="flex space-x-8 relative z-10 mt-4 md:mt-0">
                        <Gauge 
                          value={result.riskScore} 
                          title="Risk Score" 
                          color={result.riskScore < 40 ? "text-emerald-500" : result.riskScore < 70 ? "text-orange-500" : "text-red-500"} 
                        />
                        <Gauge 
                          value={result.confidenceScore} 
                          title="Confidence" 
                          color="text-blue-500" 
                        />
                      </div>
                    </div>

                    {/* Metrics Grid */}
                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                      <ScoreCard
                        title="Followers"
                        value={result.metrics.followers_count.toLocaleString()}
                        icon={<Users className="w-5 h-5" />}
                        delay={0.1}
                      />
                      <ScoreCard
                        title="Following"
                        value={result.metrics.following_count.toLocaleString()}
                        icon={<Users className="w-5 h-5 opacity-50" />}
                        delay={0.2}
                      />
                      <ScoreCard
                        title="Posts"
                        value={result.metrics.posts_count.toLocaleString()}
                        icon={<FileText className="w-5 h-5" />}
                        delay={0.3}
                      />
                      <ScoreCard
                        title="Verified"
                        value={result.metrics.verified_status ? "YES" : "NO"}
                        colorClass={result.metrics.verified_status ? "text-emerald-400" : "text-slate-500"}
                        icon={<CheckCircle2 className="w-5 h-5" />}
                        delay={0.4}
                      />
                    </div>

                    {/* Explanation Section */}
                    <motion.div
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.5, delay: 0.5 }}
                      className="bg-[#161922] border border-white/5 rounded-2xl p-6 relative"
                    >
                      <h4 className="text-sm font-semibold text-white flex items-center gap-2 mb-4">
                        <Info className="w-4 h-4 text-blue-400" />
                        Technical Explanation
                      </h4>
                      <p className="text-sm text-slate-400 leading-relaxed">
                        {result.technicalExplanation}
                      </p>
                      
                      <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div className="p-4 rounded-lg bg-[#0F1117] border border-white/5">
                          <div className="text-[10px] text-slate-500 uppercase font-bold mb-2">Identity Consistency</div>
                          <div className="flex items-center">
                            <div className="w-full bg-slate-800 rounded-full h-1.5 mr-3">
                              <div className="bg-blue-500 h-1.5 rounded-full" style={{ width: `${result.metrics.identity_consistency_score}%` }}></div>
                            </div>
                            <span className="text-xs font-mono w-6 text-white">{result.metrics.identity_consistency_score}%</span>
                          </div>
                        </div>
                        <div className="p-4 rounded-lg bg-[#0F1117] border border-white/5">
                          <div className="text-[10px] text-slate-500 uppercase font-bold mb-2">Randomness Score</div>
                          <div className="flex items-center">
                            <div className="w-full bg-slate-800 rounded-full h-1.5 mr-3">
                              <div className="bg-orange-500 h-1.5 rounded-full" style={{ width: `${result.metrics.username_randomness_score}%` }}></div>
                            </div>
                            <span className="text-xs font-mono w-6 text-white">{result.metrics.username_randomness_score}%</span>
                          </div>
                        </div>
                        <div className="p-4 rounded-lg bg-[#0F1117] border border-white/5">
                          <div className="text-[10px] text-slate-500 uppercase font-bold mb-2">Activity Pattern</div>
                          <div className="flex items-center">
                            <div className="w-full bg-slate-800 rounded-full h-1.5 mr-3">
                              <div className="bg-purple-500 h-1.5 rounded-full" style={{ width: `${result.metrics.activity_pattern_score}%` }}></div>
                            </div>
                            <span className="text-xs font-mono w-6 text-white">{result.metrics.activity_pattern_score}%</span>
                          </div>
                        </div>
                      </div>
                    </motion.div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>
    </div>
  );
}
